# Generated by Django 5.0.14 on 2026-04-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="registration_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
