# Generated by Django 5.0.14 on 2026-03-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255, unique=True)),
                ("regular_price", models.IntegerField()),
                ("sale_price", models.IntegerField()),
                ("sms_count", models.IntegerField()),
                ("stock_count", models.IntegerField()),
                ("subscription_length", models.IntegerField()),
                (
                    "subscription_period",
                    models.CharField(
                        choices=[("day", "Kun"), ("month", "Oy"), ("year", "Yil")],
                        max_length=255,
                    ),
                ),
                ("subscription_info", models.TextField()),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.IntegerField()),
            ],
        ),
    ]
