# Generated by Django 5.0.14 on 2026-03-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("regular_price", models.PositiveIntegerField()),
                ("sale_price", models.PositiveIntegerField()),
                ("sms_count", models.PositiveIntegerField()),
                ("stock_count", models.PositiveIntegerField()),
                ("length", models.PositiveIntegerField()),
                (
                    "period",
                    models.CharField(
                        choices=[("day", "Kun"), ("month", "Oy"), ("year", "Yil")],
                        max_length=255,
                    ),
                ),
                ("info", models.TextField()),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
