# Generated by Django 5.0.14 on 2026-03-05 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionproducts",
            old_name="subscription_info",
            new_name="info",
        ),
        migrations.RenameField(
            model_name="subscriptionproducts",
            old_name="subscription_length",
            new_name="length",
        ),
        migrations.RenameField(
            model_name="subscriptionproducts",
            old_name="product_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="subscriptionproducts",
            old_name="subscription_period",
            new_name="period",
        ),
    ]
