# Generated by Django 5.0.14 on 2026-03-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscription",
            "0002_rename_subscription_info_subscriptionproducts_info_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionproducts",
            name="length",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="subscriptionproducts",
            name="order",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="subscriptionproducts",
            name="regular_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="subscriptionproducts",
            name="sale_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="subscriptionproducts",
            name="sms_count",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="subscriptionproducts",
            name="stock_count",
            field=models.PositiveIntegerField(),
        ),
    ]
