# Generated by Django 5.0.14 on 2026-03-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0003_alter_subscriptionproducts_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionproducts",
            name="order",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
